# Generated by Django 4.0.3 on 2022-06-23 02:38

import ManageMachine.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.core.management import call_command


def load_fixture(apps, schema_editor):
    call_command('loaddata', 'ManageMachine/fixture/machine_initial.json', app_label='ManageMachine')
    call_command('loaddata', 'ManageMachine/fixture/machine_time_initial.json', app_label='ManageMachine')

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Csv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv', models.FileField(upload_to=ManageMachine.models.getUploadPath, validators=[django.core.validators.FileExtensionValidator(['csv'])])),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='号機名')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(blank=True, max_length=255, null=True, verbose_name='受注番号')),
                ('branch', models.IntegerField(blank=True, null=True, verbose_name='枝番号')),
                ('start', models.DateTimeField(verbose_name='開始日時')),
                ('end', models.DateTimeField(verbose_name='終了日時')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ManageMachine.machine')),
            ],
        ),
        migrations.CreateModel(
            name='MachineTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField()),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ManageMachine.machine')),
            ],
        ),
        migrations.RunPython(load_fixture),
    ]
